project:
  type: website

website:
  title: "The Data Sandbox"
  site-url: https://datasandbox.netlify.app
  description: "The Data Sandbox is a collection of Data Science projects and discussions on Data Science topics."
  twitter-card:
    creator: "@edney_mark"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mark-edney
      - icon: twitter
        href: https://twitter.com/edney_mark
      - icon: rss
        href: index.xml

format:
  html:
    theme: yeti
    css: styles.css

editor: source



