project:
  type: website

website:
  title: "The Data Sandbox"
  site-url: https://datasandbox.netlify.app
  description: "The Data Sandbox is a collection of Data Science projects and discussions on Data Science topics."
  twitter-card:
    creator: "@edney_mark"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mark-edney
      - icon: twitter
        href: https://twitter.com/edney_mark
      - icon: rss
        href: index.xml
      - icon: archive
        href: archive.html
        
  margin-header: |
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4108863678822570"
     crossorigin="anonymous"></script>
        
  comments:
    giscus:
      repo: mark-edney/Sandbox_quarto
      
  google-analytics: "G-VNSWDG9ZWF"

format:
  html:
    theme: yeti
    css: styles.css

editor: source

execute:
  freeze: auto



